name: Pipeline de integração contínua (CI)

#gatilhos: dispara o pipiline em pushes e pull requests na branch principal
on:
  push:
    branches: [ "main" , "master" ]
  pull_request:
    branches: [ "main" , "master" ]
jobs:
   testes-e-validacao:
      runs-on: ubuntu-latest
   steps:
      - name: baixar codigo-fonte
        uses: actions/checkout@v4
#step 2: configura o ambiente node.js
      - name: configurar o Node.js
        uses: actions/setup-node@v4

        with:
          node-version: '20'
          cache: 'npm'
#step 3: instalar dependencias de forma consistente
      - name: instalar dependencias
        run: npm ci
#step 4: analise estatica com linter
      - name: executar linter
        run: npm run lint

#step 5: testes unitarios
      - name: executar testes unitarios
        run: npm test
#step 6: analise  estatica  de segurança basica (sast)
      - name : verificaçao de segurança de dependencias (SAST)
        run: npm audit --audit-level=high

      - name: simular falha
        run: exit 1

